db = db.getSiblingDB("recipeDB");
if (db.getCollection("recipeCollection"))
  db.getCollection("recipeCollection").drop();
db.createCollection("recipeCollection");
collection = db.getCollection("recipeCollection");
collection.insertMany([
  {
    recipeID: "1",
    image:
      "https://www.allrecipes.com/thmb/bD7P4OevmnchtwY4n-ONughl3Dw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/734000-7300fdbd8f4945c089d512ffab659061.jpg",
    name: "Vanilla Ice Cream",
    ingredients: [
      "2 cups heavy whipping cream",
      "2 cups half-and-half cream",
      "¾ cup white sugar",
      "1 tablespoon vanilla extract",
    ],
    steps: [
      "Whisk heavy cream and half-and-half together in a large bowl. Gradually whisk in sugar until blended, then whisk in vanilla. Cover and refrigerate until very cold, at least 3 hours or up to 3 days.",
      "Remove from the refrigerator and whisk mixture to blend. Pour into an ice cream maker and freeze according to the manufacturer's instructions, about 20 minutes. Transfer to an airtight container and freeze until firm, about 4 hours.",
    ],
    source: "https://www.allrecipes.com/recipe/8314/vanilla-ice-cream/",
  },
  {
    recipeID: "2",
    image: "",
    name: "Homemade Vanilla Ice Cream",
    ingredients: [
      "2 cups heavy whipping cream",
      "2 cups half-and-half cream",
      "1 cup sugar",
      "2 teaspoons vanilla extract",
    ],
    steps: [
      "Combine all ingredients, stirring to dissolve sugar completely. Fill cylinder of ice cream maker no more than two-thirds full; freeze according to manufacturer's directions. (Refrigerate any remaining mixture until ready to freeze.) Serve immediately or store in covered containers in freezer.",
    ],
    source: "www.tasteofhome.com/recipes/homemade-vanilla-ice-cream/",
  },
  {
    recipeID: "3",
    image: "",
    name: "Pan-Seared Steak with Garlic Butter",
    ingredients: [
      "2 lbs New York Strip Steaks (2 steaks), or Ribeye or Top Sirloin Steaks (1 lb each steak, 1 1/4” thick)",
      "1/2 Tbsp vegetable oil, or any high heat cooking oil like canola or extra light olive oil",
      "1 1/2 tsp sea salt",
      "1 tsp black pepper, freshly ground",
      "2 Tbsp unsalted butter",
      "2 cloves garlic, peeled and quartered",
      "1 sprig fresh rosemary",
    ],
    steps: [
      " Thoroughly pat steak dry with paper towels. Just before cooking, generously season with 1 1/2 tsp salt and 1 tsp black pepper",
      "Heat the cast iron pan until hot then add 1/2 Tbsp oil over medium-high heat, swirling to coat. Once the oil is very hot, add steaks to the skillet. Sear the steaks on the first side for 4 minutes until a brown crust has formed then flip and cook another 3-4 minutes. Using tongs, turn the steak on its sides to render the white fat and sear the edges (1-minute per edge).",
      "Reduce heat to medium and immediately add 2 Tbsp butter, quartered garlic cloves and rosemary to the pan. Spoon the butter sauce over the steak, tilting the pan to get butter on your spoon. Continue spooning the sauce over the steak for a minute or until the steak is about 5-10 degrees from your desired doneness (the temperature will continue to rise another 5-10 degrees while steaks rest).",
      "Transfer steak to a cutting board, loosely cover and rest 10 minutes before slicing into 1/2\" strips to serve. Spoon extra butter sauce over sliced steak to serve.',",
    ],
    source: "https://natashaskitchen.com/pan-seared-steak/",
  },
  {
    recipeID: "4",
    image: "",
    name: "Basic Mashed Potatoes",
    ingredients: [
      "2 pounds baking potatoes, peeled and quartered",
      "3 cloves garlic, peeled, or to taste (Optional)",
      "1 cup milk",
      "2 tablespoons butter",
      "salt and ground black pepper to taste",
    ],
    steps: [
      "Bring a large pot of salted water to a boil. Add potatoes and garlic, lower heat to medium, and simmer until potatoes are tender, 15 to 20 minutes.",
      "When the potatoes are almost finished, heat milk and butter in a small saucepan over low heat until butter is melted.",
      "Drain potatoes and return to the pot. Slowly add warm milk mixture, blending it in with a potato masher or electric mixer until potatoes are smooth and creamy. Season with salt and pepper.",
    ],
    source: "https://www.allrecipes.com/recipe/24771/basic-mashed-potatoes/",
  },
  {
    recipeID: "5",
    image: "",
    name: "Homemade Pasta",
    ingredients: [
      "2 cups all-purpose flour, spooned & leveled",
      "3 large eggs",
      "½ teaspoon sea salt",
      "2 tablespoons butter",
      "½ tablespoon extra-virgin olive oil",
    ],
    steps: [
      "Place the flour on a clean work surface and make a nest. Add the eggs, olive oil, and salt to the center and use a fork to gently break up the eggs, keeping the flour walls intact as best as you can. Use your hands to gently bring the flour inward to incorporate. Continue working the dough with your hands to bring it together into a shaggy ball.",
      "Knead the dough for 8 to 10 minutes. At the beginning, the dough should feel pretty dry, but stick with it! It might not feel like it’s going to come together, but after 8-10 minutes of kneading, it should become cohesive and smooth. If the dough still seems too dry, sprinkle your fingers with a tiny bit of water to incorporate. If it’s too sticky, dust more flour onto your work surface. Shape the dough into a ball, wrap in plastic wrap, and let rest at room temperature for 30 minutes.",
      "Dust 2 large baking sheets with flour and set aside.",
      "Slice the dough into four pieces. Gently flatten one into an oval disk. Run the dough through the Pasta Roller Attachment or a pasta maker three times on level 1 (the widest setting).",
      "Set the dough piece onto a countertop or work surface. Fold both short ends in to meet in the center, then fold the dough in half to form a rectangle",
      "Run the dough through the pasta roller three times on level 2, three times on level 3, and one time each on levels 4, 5, and 6.",
      "Lay half of the pasta sheet onto the floured baking sheet and sprinkle with flour before folding the other half on top. Sprinkle more flour on top of the second half. Every side should be floured so that your final pasta noodles won't stick together.",
      "Repeat with remaining dough.",
      "Run the pasta sheets through the Pasta Cutter Attachment. Repeat with remaining dough. Cook the pasta in a pot of salted boiling water for 1 to 2 minutes.",
    ],
    source: "https://www.loveandlemons.com/homemade-pasta-recipe/",
  },
  {
    recipeID: "6",
    image: "",
    name: "Homemade Bread",
    ingredients: [
      "2 cups of warm water: (105-115 degrees)",
      "1 table spoon of active dry yeast",
      "1/4 cup honey or sugar",
      "2 teaspoons salt",
      "2 Tablespoons oil (canola or vegetable)",
      "4 - 5 1/2 cups all-purpose or bread flour",
    ],
    steps: [
      "Prepare the dough: In a large bowl or stand mixer add the yeast, water and a pinch of the sugar or honey. Allow to rest for 5-10 minutes until foaming and bubbly. (This is called “proofing” the yeast, to make sure it is active. If it doesn’t foam, the yeast is no good, and you need to start over with fresh yeast).",
      "Add remaining sugar or honey, salt, oil, and 3 cups of flour. Mix to combine.",
      "Knead the dough: Mix the dough for 4-5 minutes on medium speed (or knead with your hands on a lightly floured surface, for 5-8 minutes).",
      "First Rise: Grease a large bowl with oil or cooking spray and place the dough inside, turning to coat. Cover with a dish towel or plastic wrap and allow to rise in a warm place* until doubled in size, about 1 ½ hours.",
      "Spray two 9x5'' bread pans generously with cooking spray on all sides. (I also like to line the bottom of the pans with a small piece of parchment or wax paper, but this is optional.)",
      "Punch the dough down well to remove air bubbles. Divide into two equal portions. Shape each ball into long logs and place into greased loaf pans.",
      "Second rise: Spray two pieces of plastic wrap with cooking spray and lay them gently over the pans. Allow dough to rise again for about 45 minutes to one hour, or until risen about 1 inch above the loaf pans. Gently removing covering.",
      "Bake: Preheat oven to 350 F. Bake bread for about 30-33 minutes, or until golden brown on top. Give the top of a loaf a gentle tap; it should sound hollow.",
      "Invert the loaves onto a wire cooling rack. Brush the tops with butter and allow to cool for at least 10 minutes before slicing.",
      "Once cool, store in an airtight container or bag for 2-3 days at room temperature, or up to 5 days in the refrigerator.",
    ],
    source: "https://tastesbetterfromscratch.com/bread-recipe/",
  },
  {
    recipeID: "7",
    image: "",
    name: "Best Homemade Pizza (1 Hour or Overnight)",
    ingredients: [
      "1 16 ounce ball of pizza dough, 12 to 16 ounces is fine",
      "1 tablespoon olive oil, for rubbing dough",
      "1 cup pizza sauce",
      "3 ounces thinly sliced mozzarella cheese",
      "5 ounces shredded mozzarella cheese, about 1 and 1/4 cups",
      "2.5 ounces pepperoni , about half a 5 oz package",
      "2 tablespoons shredded parmesan cheese",
    ],
    steps: [
      "NOTE: The ingredient list has the amount of toppings you need to make one 12-inch pizza. If you followed my pizza dough recipe, you will have 2 balls of dough. If you want to make them both right away, be sure to double the topping ingredients shown here.",
      "Place a pizza stone in the bottom third of your oven. (place a rimmed baking sheet or a pizza pan in the oven if you don't have a stone.)",
      "Preheat your oven to 550 degrees F, or as high as it will go (at least 475.) Let the stone preheat for 30 minutes. I don't care when your oven beeps to tell you it's at temperature. Set a timer, 30 minutes at least!",
      "Prepare a work surface. I prefer to rub my counter with oil, but you can lightly dust it with flour if you have a very sticky dough. (Too much flour can turn your dough tough.)",
      "Roll out the dough. Place your ball of pizza dough in the center of your prepared work surface and use your hands to press it down, starting from the center. Keep gently patting out the dough, moving the dough outward from the center. I usually use my hands for pizza dough, gently patting and stretching (and yes, picking it up and maybe even tossing!), but you can also use a rolling pin. Make sure to keep rotating the pin so that you get a roughly circular shape. It doesn't have to be perfect! Even if you have used a rolling pin, I like to use my fingers afterward to shape the edges into a thicker crust. See photos.",
      "Continue patting and stretching the dough gently with your hands until it is about 12 inches across.",
      "Transfer the dough to a square of parchment paper. I highly recommend using parchment paper because it’s SO much easier transferring your pizza into the oven. You can pick it up carefully with your hands and rearrange it on the paper, or wrap it around your rolling pin to help transfer. (I've tried rolling the dough out directly onto parchment paper. It doesn't work well.) Make sure you stretch out the dough so that it is about 12 inches.",
      "Drizzle about a tablespoon of olive oil over the top of your dough. Use your hands or a pastry brush to rub the oil all over the top of the dough, especially the edges of the crust. This layer of oil helps provide a barrier between the toppings and the dough, helping it cook more evenly.",
      "If you love a thicker crust pizza, let the rolled-out dough rest for 10 minutes. You can skip this rest no problem.",
      "Par bake. Once the oven is up to temperature, we are going to do a 1 to 2 minute par bake. This step is technically not necessary, but I never skip it. It guarantees not only a thoroughly cooked crust, but a nice and crispy one. Nobody wants a doughy pizza, yuck. (If you want to skip it, you can proceed with topping your pizza).",
      "Pulling on the edge of the parchment paper, slide your pizza dough onto your pizza peel or flat baking sheet. Open the oven and pull on the parchment paper again to slide the pizza dough and the parchment paper onto the hot hot pizza stone (or pizza pan). Your whole body is basically inside the oven during this procedure so please be careful and make sure there are no toddlers running around who could climb right in and burn to death (these are the thoughts that keep me up at night).",
      "Shut the oven door and par bake for 1-2 minutes, until the dough is slightly puffed. Set a timer, don't walk away!",
      "Pull on the parchment paper again to transfer the half-baked dough back onto your pizza peel. Keep the oven door shut as much as possible so you don't lose heat. Poke down any large bubbles on your crust.",
      "Top your pizza. Leave the crust on the peel while you add your toppings.",
      "Add 1 cup of pizza sauce (I like to spread it around with a ladle).",
      "Add 3 ounces thinly sliced mozzarella, and then top with 5 ounces of shredded mozzarella. I like a lot of cheese and this is about the max amount you can add without weighing down your pizza so much that it doesn't cook all the way through. This isn't the Bible, you can eyeball the amounts on cheese, just keep in mind there is a limit if you want a properly cooked pizza.",
      "Add about a half package of pepperoni (or olives, mushrooms, ham and pineapple, sausage, red onions, or literally any toppings you want. See post for ideas.)",
      "Sprinkle 2 tablespoons shredded parmesan cheese over your toppings.",
      "Bake the pizza. (See note if you don't have a pizza stone*) Transfer the pizza back onto the pizza stone (or pan), this time without the parchment paper. You want the pizza to do its final bake directly on the stone. (The stone is porous and absorbs moisture, giving you a crispier crust.) Your crust is sturdy enough after the 1-2 minute par bake that it shouldn't be too hard to push the pizza onto the stone without the paper.",
      "Bake the pizza for about 8-12 minutes. This is going to depend on how hot your oven is, and how thick your pizza is. The edges of the crust should be golden brown, and the cheese should be bubbly and also starting to lightly brown. If you don't have a pizza stone, use a spatula to lift the edge of your pizza to make sure that it is browning all across the center on bottom. If the bottom is still white, you are looking at a doughy pizza. No thanks. Leave it in longer.",
      "If the top of your pizza is browning too quickly but the bottom crust isn't done, tent the top of the pizza with foil to slow browning.",
      "Remove your pizza from the oven using the pizza peel. Slide it directly onto a cooling rack to help keep that bottom crust from getting soggy. Let cool a couple minutes, then transfer to a cutting board. Slice into 8 pieces and devour!",
    ],
    source: "https://thefoodcharlatan.com/homemade-pizza-recipe/",
  },
]);
